"""Canonical skill -> alias map used by the resume parser and job matcher."""

SKILL_VOCABULARY: dict[str, list[str]] = {
    # Languages
    "python": ["python"],
    "javascript": ["javascript", "js", "ecmascript"],
    "typescript": ["typescript", "ts"],
    "java": ["java"],
    "c++": ["c++", "cpp"],
    "c#": ["c#", "csharp"],
    "go": ["golang", "go lang"],
    "rust": ["rust"],
    "php": ["php"],
    "ruby": ["ruby", "ruby on rails", "rails"],
    "kotlin": ["kotlin"],
    "swift": ["swift"],
    "scala": ["scala"],
    "r": ["r programming", "r language"],
    "sql": ["sql"],
    "bash": ["bash", "shell scripting"],
    # Frontend
    "react": ["react", "react.js", "reactjs"],
    "next.js": ["next.js", "nextjs"],
    "vue": ["vue", "vue.js", "vuejs"],
    "angular": ["angular", "angularjs"],
    "redux": ["redux"],
    "tailwind css": ["tailwind", "tailwindcss", "tailwind css"],
    "html": ["html", "html5"],
    "css": ["css", "css3"],
    "sass": ["sass", "scss"],
    "webpack": ["webpack"],
    "vite": ["vite"],
    # Backend & APIs
    "fastapi": ["fastapi"],
    "django": ["django"],
    "flask": ["flask"],
    "node.js": ["node.js", "nodejs", "node"],
    "express": ["express", "express.js", "expressjs"],
    "nest.js": ["nest.js", "nestjs"],
    "spring boot": ["spring boot", "springboot", "spring"],
    "graphql": ["graphql"],
    "rest api": ["rest", "rest api", "restful", "restful api"],
    "grpc": ["grpc"],
    "microservices": ["microservices", "microservice"],
    "celery": ["celery"],
    # Data stores
    "mongodb": ["mongodb", "mongo"],
    "postgresql": ["postgresql", "postgres"],
    "mysql": ["mysql", "mariadb"],
    "redis": ["redis"],
    "elasticsearch": ["elasticsearch", "elastic search"],
    "sqlite": ["sqlite"],
    "dynamodb": ["dynamodb", "dynamo db"],
    "cassandra": ["cassandra"],
    # ORM / data access
    "prisma": ["prisma"],
    "sqlalchemy": ["sqlalchemy"],
    "beanie": ["beanie"],
    "mongoose": ["mongoose"],
    "hibernate": ["hibernate"],
    # Cloud & DevOps
    "docker": ["docker", "containerisation", "containerization"],
    "kubernetes": ["kubernetes", "k8s"],
    "aws": ["aws", "amazon web services"],
    "azure": ["azure", "microsoft azure"],
    "gcp": ["gcp", "google cloud"],
    "terraform": ["terraform"],
    "jenkins": ["jenkins"],
    "github actions": ["github actions"],
    "ci/cd": ["ci/cd", "cicd", "continuous integration"],
    "linux": ["linux", "unix"],
    "nginx": ["nginx"],
    # Data / AI
    "machine learning": ["machine learning", "ml"],
    "deep learning": ["deep learning"],
    "tensorflow": ["tensorflow"],
    "pytorch": ["pytorch", "torch"],
    "scikit-learn": ["scikit-learn", "scikit learn", "sklearn"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "nlp": ["nlp", "natural language processing"],
    "spacy": ["spacy"],
    "data analysis": ["data analysis", "data analytics"],
    "data visualization": ["data visualization", "data visualisation", "tableau", "power bi"],
    "etl": ["etl", "data pipeline", "data pipelines"],
    "spark": ["spark", "apache spark", "pyspark"],
    "airflow": ["airflow", "apache airflow"],
    # Testing & quality
    "pytest": ["pytest"],
    "jest": ["jest"],
    "cypress": ["cypress"],
    "selenium": ["selenium"],
    "unit testing": ["unit testing", "unit test", "unit tests"],
    "playwright": ["playwright"],
    "tdd": ["tdd", "test driven development"],
    # Product / process
    "agile": ["agile", "scrum", "kanban"],
    "jira": ["jira"],
    "git": ["git", "github", "gitlab", "bitbucket"],
    "communication": ["communication", "communication skills"],
    "leadership": ["leadership", "team lead", "mentoring"],
    "problem solving": ["problem solving", "problem-solving", "analytical skills"],
    "project management": ["project management", "stakeholder management"],
    # Design
    "figma": ["figma"],
    "ui/ux": ["ui/ux", "ui design", "ux design", "user experience"],
    "photoshop": ["photoshop"],
    # Business / non-tech
    "sales": ["sales", "business development"],
    "marketing": ["marketing", "digital marketing", "seo", "sem"],
    "accounting": ["accounting", "bookkeeping", "tally"],
    "excel": ["excel", "advanced excel", "spreadsheets"],
    "customer service": ["customer service", "customer support"],
    "recruitment": ["recruitment", "talent acquisition", "hiring"],
    "hr": ["hr", "human resources"],
    "finance": ["finance", "financial analysis", "fp&a"],
    "content writing": ["content writing", "copywriting", "technical writing"],
}
